"""add token_hash and activated_at to users

Revision ID: 0dd0bd7c3a1c
Revises: 5d526541761f
Create Date: 2026-06-09 00:23:04.216074
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dd0bd7c3a1c'
down_revision: Union[str, None] = '5d526541761f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token_hash', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'users', ['token_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'activated_at')
    op.drop_column('users', 'token_hash')
    # ### end Alembic commands ###
