"""add mode column to request_logs

Revision ID: 7a92861165ad
Revises: 847b58f0e80d
Create Date: 2026-06-09 01:10:56.253928
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a92861165ad'
down_revision: Union[str, None] = '847b58f0e80d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_logs', sa.Column('mode', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request_logs', 'mode')
    # ### end Alembic commands ###
